#
#   Copyright (c) 2017-2018 Joy Diamond.  All rights reserved.
#
J = ../Mirror/source/link/crystal

JACINTH_FILES = \
    ../Mirror/pom.xml \
    $J/Alpha/Main.java \
    $J/Alpha/Shape.java \
    $J/Gem/Core/ArrayFunctions.java \
    $J/Gem/Core/Gem.java \
    $J/Gem/Core/Gem_List.java \
    $J/Gem/Core/Gem_Map.java \
    $J/Gem/Core/Gem_Object.java \
    $J/Gem/Core/Gem_StringBuilder.java \
    $J/Gem/Core/Gem_StringMap.java \
    $J/Gem/Core/Gem_StringSet.java \
    $J/Gem/Core/Zone.java \
    $J/Gem/Exception/AssertionError.java \
    $J/Gem/Exception/ExceptionFunctions.java \
    $J/Gem/Format/AdornmentSegmentFormatter.java \
    $J/Gem/Format/ArgumentSegmentFormatter_Inspection.java \
    $J/Gem/Format/ArgumentSegmentFormatter.java \
    $J/Gem/Format/Map__String__ArgumentSegmentFormatter_Inspection.java \
    $J/Gem/Format/MessageFormatter_1__Prefix.java \
    $J/Gem/Format/MessageFormatter_2.java \
    $J/Gem/Format/MessageFormatter_3.java \
    $J/Gem/Format/MessageFormatter_4.java \
    $J/Gem/Format/MessageFormatter_5.java \
    $J/Gem/Format/MessageFormatter_Base.java      \
    $J/Gem/Format/MessageFormatter_Many.java \
    $J/Gem/Format/MethodNameSegmentFormatter.java \
    $J/Gem/Format/NormalSegmentFormatter.java \
    $J/Gem/Format/ParseFormat.java \
    $J/Gem/Format/PortraySegmentFormatter.java \
    $J/Gem/Format/SegmentFormatter_Inspection.java \
    $J/Gem/Format/StringSegmentFormatter.java \
    $J/Gem/Inspection/Comparable_Inspection.java \
    $J/Gem/Inspection/Gem_Reference_Inspection.java \
    $J/Gem/Inspection/Inspection.java \
    $J/Gem/Inspection/World_Inspection.java \
    $J/Gem/Interface/Gem_Comparable.java \
    $J/Gem/Interface/Gem_ComparableReference_Interface.java \
    $J/Gem/Interface/Gem_QueueableReference_Interface.java \
    $J/Gem/Interface/Gem_Referenceable_Interface.java \
    $J/Gem/Interface/Gem_Reference_Interface.java \
    $J/Gem/Interface/Inspectable.java \
    $J/Gem/Interface/MessageFormattable.java \
    $J/Gem/Interface/SegmentFormattable.java \
    $J/Gem/Interface/Storehouse_String__Interface.java \
    $J/Gem/Portray_1/AnalyzeString.java \
    $J/Gem/Portray_1/AsciiTable.java \
    $J/Gem/Portray_1/BuildStringState.java \
    $J/Gem/Portray_1/EphemeralStringState.java \
    $J/Gem/Portray_1/OverallStringState.java \
    $J/Gem/Portray_1/PortrayString.java \
    $J/Gem/Portray_2/AnalyzeString.java \
    $J/Gem/Portray_2/EphemeralStringState.java \
    $J/Gem/Portray_2/OverallStringState.java \
    $J/Gem/Support/Gem_ComparableReference_Cache.java \
    $J/Gem/Support/Gem_ReferenceQueue.java \
    $J/Gem/Support/Gem_TimeUnit.java \
    $J/Gem/Support/Gem_WeakReference.java \
    $J/Gem/Support/Inspection_Cache.java \
    $J/Gem/Support/Storehouse_AdornmentSegmentFormatter.java \
    $J/Gem/Support/Storehouse_MessageFormattable.java \
    $J/Gem/Support/Storehouse_NormalSegmentFormatter.java \
    $J/Gem/Support/Storehouse_PortraySegmentFormatter.java \
    $J/Gem/Support/Storehouse_SmallList.java \
    $J/Gem/Support/Storehouse_String.java \
    $J/Gem/Support/Storehouse_StringSegmentFormatter.java \
    $J/Gem/Support/Temporary_Storehouse_String.java \
    $J/Gem/Support/UniqueName.java \
    $J/Gem/Support/World_Integer_Cache.java \
    $J/Gem/Support/World_Integer_EnduringReference.java \
    $J/Gem/Support/World_Integer_Key.java \
    $J/Gem/Support/World_Integer_WeakReference.java \
    $J/Gem/Support/World_String_Cache.java \
    $J/Gem/Support/World_String_EnduringReference.java \
    $J/Gem/Support/World_String_Key.java \
    $J/Gem/Support/World_String_WeakReference.java \
    $J/Gem/UnitTest/UnitTest_Gem.java \
    $J/Gem/UnitTest/UnitTest_PortrayString.java \
    $J/Gem/UnitTest/World_String_WeakReference_PhantomReference.java \
    $J/Gem/World/World_Integer.java \
    $J/Gem/World/World_String.java \
    $J/Mirror/MirrorModule.java \
    $J/Mirror/MirrorProxy.java \
    $J/Mirror/Mirror_String.java \
    $J/Mirror/UnitTest/UnitTest.java \
    $J/Mirror/UnitTest/UnitTest_Java.java \
    $J/Mirror/UnitTest/UnitTest_Mirror.java \
    $J/Mock/Shape.java

WORK_FILES = \
    Makefile \
    z.java

FILES = \
    $(JACINTH_FILES) \
    $(WORK_FILES)


all: clean files links


clean:
	rm -f *.old *.new
	rm -f ae.java af.java ads.java ags.java agsi.java am.java am.xml as.java at.java
	rm -f bss.java
	rm -f ci.java
	rm -f ef.java ess.java ess1.java
	rm -f files
	rm -f gcrc.java ge.java gl.java go.java gm.java gri.java grq.java
	rm -f   gsb.java gsm.java gss.java gtu.java gwr.java gz.java
	rm -f igc.java igcr.java igqr.java igr.java igra.java ic.java ii.java in.java ishs.java isf.java imf.java
	rm -f ks.java
	rm -f m m1.java m1p.java m1s.java m2.java m3.java m4.java m5.java mb.java mm.java mn.java msa.java
	rm -f ns.java
	rm -f oss.java oss1.java
	rm -f pf.java ps.java psc.java px.java
	rm -f qn.java
	rm -f sha.java shl.java shm.java shn.java shp.java shs.java shsf.java sfi.java ss.java
	rm -f tshs.java
	rm -f ut.java utg.java utj.java utm.java uty.java
	rm -f vm.java vp.java vs.java
	rm -f wi.java wic.java wie.java wik.java win.java wiw.java
	rm -f   ws.java wsc.java wse.java wsk.java wsw.java wswp.java
	rm -f ys.java
	rm -f za.java za1.java


files:
	echo $(FILES) >files.1.tmp
	tr ' ' '\n' <files.1.tmp >files.2.tmp
	mv files.2.tmp files


links:
	ln -s $J/Gem/Format/AdornmentSegmentFormatter.java                          ads.java
	ln -s $J/Gem/Exception/AssertionError.java                                  ae.java
	ln -s $J/Gem/Core/ArrayFunctions.java                                       af.java
	ln -s $J/Gem/Format/ArgumentSegmentFormatter.java                           ags.java
	ln -s $J/Gem/Format/ArgumentSegmentFormatter_Inspection.java                agsi.java
	ln -s $J/Alpha/Main.java                                                    am.java
	ln -s $J/Alpha/Shape.java                                                   as.java
	ln -s $J/Gem/Portray_1/AsciiTable.java                                      at.java
	ln -s $J/Gem/Portray_1/BuildStringState.java                                bss.java
	ln -s $J/Gem/Inspection/Comparable_Inspection.java                          ci.java
	ln -s $J/Gem/Exception/ExceptionFunctions.java                              ef.java
	ln -s $J/Gem/Portray_2/EphemeralStringState.java                            ess.java
	ln -s $J/Gem/Portray_1/EphemeralStringState.java                            ess1.java
	ln -s $J/Gem/Support/Gem_ComparableReference_Cache.java                     gcrc.java
	ln -s $J/Gem/Core/Gem.java                                                  ge.java
	ln -s $J/Gem/Core/Gem_List.java                                             gl.java
	ln -s $J/Gem/Core/Gem_Map.java                                              gm.java
	ln -s $J/Gem/Core/Gem_Object.java                                           go.java
	ln -s $J/Gem/Inspection/Gem_Reference_Inspection.java                       gri.java
	ln -s $J/Gem/Support/Gem_ReferenceQueue.java                                grq.java
	ln -s $J/Gem/Core/Gem_StringBuilder.java                                    gsb.java
	ln -s $J/Gem/Core/Gem_StringMap.java                                        gsm.java
	ln -s $J/Gem/Core/Gem_StringSet.java                                        gss.java
	ln -s $J/Gem/Support/Gem_TimeUnit.java                                      gtu.java
	ln -s $J/Gem/Support/Gem_WeakReference.java                                 gwr.java
	ln -s $J/Gem/Core/Zone.java                                                 gz.java
	ln -s $J/Gem/Interface/Gem_Comparable.java                                  igc.java
	ln -s $J/Gem/Interface/Gem_ComparableReference_Interface.java               igcr.java
	ln -s $J/Gem/Interface/Gem_QueueableReference_Interface.java                igqr.java
	ln -s $J/Gem/Interface/Gem_Reference_Interface.java                         igr.java
	ln -s $J/Gem/Interface/Gem_Referenceable_Interface.java                     igra.java
	ln -s $J/Gem/Interface/Inspectable.java                                     ii.java
	ln -s $J/Gem/Support/Inspection_Cache.java                                  ic.java
	ln -s $J/Gem/Inspection/Inspection.java                                     in.java
	ln -s $J/Gem/Interface/MessageFormattable.java                              imf.java
	ln -s $J/Gem/Interface/Storehouse_String__Interface.java                    ishs.java
	ln -s $J/Gem/Interface/SegmentFormattable.java                              isf.java
	ln -s ../Mirror/pom.xml                                                     am.xml
	ln -s $J/Mock/Shape.java                                                    ks.java
	ln -s Makefile                                                              m
	ln -s $J/Gem/Format/MessageFormatter_1__Prefix.java                         m1p.java
	ln -s $J/Gem/Format/MessageFormatter_2.java                                 m2.java
	ln -s $J/Gem/Format/MessageFormatter_3.java                                 m3.java
	ln -s $J/Gem/Format/MessageFormatter_4.java                                 m4.java
	ln -s $J/Gem/Format/MessageFormatter_5.java                                 m5.java
	ln -s $J/Gem/Format/MessageFormatter_Base.java                              mb.java
	ln -s $J/Gem/Format/MessageFormatter_Many.java                              mm.java
	ln -s $J/Gem/Format/MethodNameSegmentFormatter.java                         mn.java
	ln -s $J/Gem/Format/Map__String__ArgumentSegmentFormatter_Inspection.java   msa.java
	ln -s $J/Gem/Format/NormalSegmentFormatter.java                             ns.java
	ln -s $J/Gem/Portray_2/OverallStringState.java                              oss.java
	ln -s $J/Gem/Portray_1/OverallStringState.java                              oss1.java
	ln -s $J/Gem/Format/ParseFormat.java                                        pf.java
	ln -s $J/Gem/Format/PortraySegmentFormatter.java                            ps.java
	ln -s $J/Gem/Support/UniqueName.java                                        qn.java
	ln -s $J/Gem/Support/Storehouse_AdornmentSegmentFormatter.java              sha.java
	ln -s $J/Gem/Support/Storehouse_SmallList.java                              shl.java
	ln -s $J/Gem/Support/Storehouse_MessageFormattable.java                     shm.java
	ln -s $J/Gem/Support/Storehouse_NormalSegmentFormatter.java                 shn.java
	ln -s $J/Gem/Support/Storehouse_PortraySegmentFormatter.java                shp.java
	ln -s $J/Gem/Support/Storehouse_String.java                                 shs.java
	ln -s $J/Gem/Support/Storehouse_StringSegmentFormatter.java                 shsf.java
	ln -s $J/Gem/Format/SegmentFormatter_Inspection.java                        sfi.java
	ln -s $J/Gem/Format/StringSegmentFormatter.java                             ss.java
	ln -s $J/Gem/Support/Temporary_Storehouse_String.java                       tshs.java
	ln -s $J/Mirror/UnitTest/UnitTest.java                                      ut.java
	ln -s $J/Gem/UnitTest/UnitTest_Gem.java                                     utg.java
	ln -s $J/Mirror/UnitTest/UnitTest_Java.java                                 utj.java
	ln -s $J/Mirror/UnitTest/UnitTest_Mirror.java                               utm.java
	ln -s $J/Gem/UnitTest/UnitTest_PortrayString.java                           uty.java
	ln -s $J/Mirror/MirrorModule.java                                           vm.java
	ln -s $J/Mirror/MirrorProxy.java                                            vp.java
	ln -s $J/Mirror/Mirror_String.java                                          vs.java
	ln -s $J/Gem/World/World_Integer.java                                       wi.java
	ln -s $J/Gem/Support/World_Integer_Cache.java                               wic.java
	ln -s $J/Gem/Support/World_Integer_EnduringReference.java                   wie.java
	ln -s $J/Gem/Support/World_Integer_Key.java                                 wik.java
	ln -s $J/Gem/Inspection/World_Inspection.java                               win.java
	ln -s $J/Gem/Support/World_Integer_WeakReference.java                       wiw.java
	ln -s $J/Gem/World/World_String.java                                        ws.java
	ln -s $J/Gem/Support/World_String_Cache.java                                wsc.java
	ln -s $J/Gem/Support/World_String_EnduringReference.java                    wse.java
	ln -s $J/Gem/Support/World_String_Key.java                                  wsk.java
	ln -s $J/Gem/Support/World_String_WeakReference.java                        wsw.java
	ln -s $J/Gem/UnitTest/World_String_WeakReference_PhantomReference.java      wswp.java
	ln -s $J/Gem/Portray_1/PortrayString.java                                   ys.java
	ln -s $J/Gem/Portray_2/AnalyzeString.java                                   za.java
	ln -s $J/Gem/Portray_1/AnalyzeString.java                                   za1.java


wc:
	wc -l \
        $(JACINTH_FILES) \
        $(WORK_FILES)

wcj:
	wc -l $(JACINTH_FILES)
