#
#   Copyright (c) 2017-2018 Joy Diamond.  All rights reserved.
#
AGATE = ../Old/Agate

AGATE_FILES = \
    $(AGATE)/RUNME.py

BERYL = ../Old/Beryl

BERYL_FILES = \
    $(BERYL)/__init__.py \
    $(BERYL)/Ask.py \
    $(BERYL)/BerylAnswer.py \
    $(BERYL)/Main.py

CRYSTAL=../Other/Crystal

CRYSTAL_FILES = \
    $(CRYSTAL)/__init__.py \
    $(CRYSTAL)/Board.py $(CRYSTAL)/BlankSquare.py \
    $(CRYSTAL)/CardRoot.py $(CRYSTAL)/ChessBishop.py $(CRYSTAL)/ChessKing.py $(CRYSTAL)/ChessKnight.py \
        $(CRYSTAL)/ChessPawn.py $(CRYSTAL)/ChessRook.py $(CRYSTAL)/Core.py \
    $(CRYSTAL)/Deck_7.py \
    $(CRYSTAL)/FrozenChessCard.py $(CRYSTAL)/FrozenCardRoot.py \
    $(CRYSTAL)/Game.py \
    $(CRYSTAL)/Main.py \
    $(CRYSTAL)/Player.py \
    $(CRYSTAL)/Square.py \
    $(CRYSTAL)/VoidSquare.py

DIAMOND=../Other/Diamond

DIAMOND_FILES = \
    $(DIAMOND)/__init__.py \
    $(DIAMOND)/Chore.py $(DIAMOND)/Core.py \
    $(DIAMOND)/Development.py \
    $(DIAMOND)/Fibonacci.py \
    $(DIAMOND)/Interval.py \
    $(DIAMOND)/LifeCycle.py \
    $(DIAMOND)/Main.py \
    $(DIAMOND)/Shared.py $(DIAMOND)/Status.py \
    $(DIAMOND)/Thread.py

GEM=../Gem/Gem

GEM_FILES = \
    $(GEM)/__init__.py \
    $(GEM)/Absent.py $(GEM)/All.py $(GEM)/Ascii.py \
    $(GEM)/Boot.py \
    $(GEM)/Cache.py $(GEM)/Cache2.py $(GEM)/Cadence.py $(GEM)/Codec.py $(GEM)/ContextManager.py $(GEM)/Core.py \
        $(GEM)/CatchException.py \
    $(GEM)/DelayedFileOutput.py $(GEM)/DroveMany.py $(GEM)/DumpCache.py \
    $(GEM)/ErrorNumber.py $(GEM)/Exception.py $(GEM)/ExecuteFile.py \
    $(GEM)/FileOutput.py $(GEM)/FileStatus.py \
    $(GEM)/Gaggle.py $(GEM)/GarbageCollection.py $(GEM)/Global.py \
    $(GEM)/Hailstone.py $(GEM)/Herd.py $(GEM)/Herd_2.py $(GEM)/Herd_3.py $(GEM)/Herd_4567.py $(GEM)/HerdMany.py \
        $(GEM)/Horde.py \
    $(GEM)/Import.py $(GEM)/IO.py \
    $(GEM)/LiquidMap.py \
    $(GEM)/Map.py $(GEM)/Method.py \
    $(GEM)/Output.py \
    $(GEM)/Path.py $(GEM)/PortrayString.py \
    $(GEM)/Rabble.py $(GEM)/RegularExpression.py \
    $(GEM)/Series.py $(GEM)/Sequence.py $(GEM)/SimpleStringIO.py $(GEM)/Sleep.py $(GEM)/StringOutput.py $(GEM)/System.py \
    $(GEM)/Traceback.py $(GEM)/Thread.py
    #
    #   Excludes:
    #       ../Gem/GeneratedConjureQuadruple.py
    #

DRAVITE = ../PPK/Dravite

DRAVITE_FILES = \
    $(DRAVITE)/Euclid.py \
    $(DRAVITE)/__init__.py \
    $(DRAVITE)/Main.py \
    $(DRAVITE)/RSA_Example.py

IVORY=../Other/Ivory

IVORY_FILES = \
    $(IVORY)/Main.py

JASPER = ../Other/Jasper

JASPER_FILES = \
    $(JASPER)/Core.py \
    $(JASPER)/Main.py \
    $(JASPER)/Parse.py $(JASPER)/Parse1.py \
        $(JASPER)/Pattern.py
    #
    #   Excludes:
    #       $(JASPER)/Match.py

LICENSE_FILES = \
    ../Other/OtherLicenses/README.txt

MARBLE = ../Other/Marble

MARBLE_FILES = \
    $(MARBLE)/Core.py \
    $(MARBLE)/GenerateAscii.py \
    $(MARBLE)/GenerateTestPortrayString.py \
    $(MARBLE)/NestedConjure.py \
    $(MARBLE)/Main.py

MELANITE = ../Other/Melanite

MELANITE_FILES = \
    $(MELANITE)/Child.py \
    $(MELANITE)/Core.py \
    $(MELANITE)/Development.py \
    $(MELANITE)/Main.py \
    $(MELANITE)/Multiprocessing.py \

ONYX = ../Other/Onyx

ONYX_FILES = \
    $(ONYX)/__init__.py \
    $(ONYX)/Core.py \
    $(ONYX)/Development.py \
    $(ONYX)/ElasticSearch.py \
    $(ONYX)/Main.py \

PEARL=../Parser/Pearl

PEARL_FILES = \
    $(PEARL)/ActionWord.py $(PEARL)/Atom.py \
    $(PEARL)/Cache.py $(PEARL)/ClassOrder.py $(PEARL)/Comment.py $(PEARL)/ConjureTreeComment.py $(PEARL)/Core.py \
        $(PEARL)/CreateMeta.py \
    $(PEARL)/Line.py \
    $(PEARL)/Method.py \
    $(PEARL)/Nub.py \
    $(PEARL)/TokenCache.py $(PEARL)/Tokenizer.py $(PEARL)/Token.py

QUARTZ = ../Parser/Quartz

QUARTZ_FILES = \
    $(QUARTZ)/Parse1.py \
    $(QUARTZ)/Core.py \
    $(QUARTZ)/Main.py \
    $(QUARTZ)/Line.py \
    $(QUARTZ)/Pattern.py \
    #
    #   Excludes:
    #       $(QUARTZ)/Match.py
    #

SAPPHIRE=../Parser/Sapphire

SAPPHIRE_FILES = \
    $(SAPPHIRE)/Atom.py \
    $(SAPPHIRE)/BinaryExpression.py $(SAPPHIRE)/BookcaseDualExpression.py $(SAPPHIRE)/BookcaseDualStatement.py \
        $(SAPPHIRE)/BookcaseExpression.py $(SAPPHIRE)/BookcaseKeywordStatement.py \
        $(SAPPHIRE)/BookcaseKeywordDualStatement.py $(SAPPHIRE)/BookcaseManyExpression.py \
        $(SAPPHIRE)/BookcaseManyFrill.py $(SAPPHIRE)/BookcaseManyStatement.py $(SAPPHIRE)/BookcaseStatement.py \
        $(SAPPHIRE)/BookcaseTriple.py $(SAPPHIRE)/BuildSymbolTable.py \
    $(SAPPHIRE)/Cache.py $(SAPPHIRE)/CallStatement.py $(SAPPHIRE)/ClassOrder.py $(SAPPHIRE)/Comment.py \
        $(SAPPHIRE)/Combine.py $(SAPPHIRE)/Core.py $(SAPPHIRE)/CreateMeta.py \
    $(SAPPHIRE)/DefinitionHeader.py $(SAPPHIRE)/Development.py $(SAPPHIRE)/DualFrill.py $(SAPPHIRE)/DualStatement.py \
        $(SAPPHIRE)/DualToken.py $(SAPPHIRE)/DualTwig.py $(SAPPHIRE)/DumpToken.py \
    $(SAPPHIRE)/Elemental.py \
    $(SAPPHIRE)/Indentation.py \
    $(SAPPHIRE)/LineMarker.py \
    $(SAPPHIRE)/Main.py $(SAPPHIRE)/ManyExpression.py $(SAPPHIRE)/ManyFrill.py $(SAPPHIRE)/MemberExpression.py \
        $(SAPPHIRE)/Method.py $(SAPPHIRE)/MosiacDefinition.py $(SAPPHIRE)/MosiacSymbol.py \
    $(SAPPHIRE)/Parse.py \
        $(SAPPHIRE)/Parse1.py $(SAPPHIRE)/Parse1Atom.py $(SAPPHIRE)/Tokenize1Header.py $(SAPPHIRE)/Parse1Call.py \
        $(SAPPHIRE)/Parse1Complex.py $(SAPPHIRE)/Parse1Expression.py $(SAPPHIRE)/Parse1ExpressionStatement.py \
        $(SAPPHIRE)/Parse1From.py $(SAPPHIRE)/Parse1Function.py $(SAPPHIRE)/Parse1Import.py \
        $(SAPPHIRE)/Parse1Simple.py \
        $(SAPPHIRE)/Parse2.py $(SAPPHIRE)/Parse3.py \
        $(SAPPHIRE)/PostfixExpression.py $(SAPPHIRE)/PrefixedDualStatement.py $(SAPPHIRE)/Priority.py \
    $(SAPPHIRE)/Pattern.py \
    $(SAPPHIRE)/QuadrupleFrill.py $(SAPPHIRE)/QuadrupleStatement.py $(SAPPHIRE)/QuadrupleToken.py \
        $(SAPPHIRE)/QuadrupleTwig.py \
    $(SAPPHIRE)/Suite.py $(SAPPHIRE)/SymbolTable.py \
    $(SAPPHIRE)/TernaryExpression.py $(SAPPHIRE)/TokenCache.py $(SAPPHIRE)/TokenTuple.py \
        $(SAPPHIRE)/Tokenize1Atom.py $(SAPPHIRE)/Tokenize1Name.py $(SAPPHIRE)/Tokenize1Operator.py \
        $(SAPPHIRE)/Tree.py $(SAPPHIRE)/TripleFrill.py $(SAPPHIRE)/TripleStatement.py $(SAPPHIRE)/TripleToken.py \
        $(SAPPHIRE)/TripleTwig.py $(SAPPHIRE)/TupleOfExpression.py \
    $(SAPPHIRE)/UnaryExpression.py \
    $(SAPPHIRE)/Whitespace.py \
    $(SAPPHIRE)/Transform.py \
    $(SAPPHIRE)/Variable.py
    #
    #   Excludes:
    #       $(SAPPHIRE)/Match.py
    #

TOPAZ=../UnitTest/Topaz

TOPAZ_FILES = \
    $(TOPAZ)/CacheSupport.py $(TOPAZ)/ConjureDual.py $(TOPAZ)/ConjureSingle.py $(TOPAZ)/ConjureQuadruple.py \
        $(TOPAZ)/ConjureTriple.py $(TOPAZ)/ConjureTreeComment.py $(TOPAZ)/Core.py \
    $(TOPAZ)/Drove.py \
    $(TOPAZ)/ExceptionChain.py \
    $(TOPAZ)/Herd.py \
    $(TOPAZ)/Main.py \
    $(TOPAZ)/Path.py $(TOPAZ)/Pattern.py $(TOPAZ)/PortrayString.py \
    $(TOPAZ)/Sequence.py $(TOPAZ)/Series.py $(TOPAZ)/StringOutput.py
    #
    #   Excludes:
    #       $(TOPAZ)/GeneratedConjureDual.py
    #       $(TOPAZ)/GeneratedConjureQuadruple.py
    #       $(TOPAZ)/GeneratedConjureTriple.py
    #       $(TOPAZ)/GeneratedNew.py
    #       $(TOPAZ)/OldConjureQuadruple.py
    #

TREMOLITE=../Tremolite/Tremolite

TREMOLITE_FILES = \
    $(TREMOLITE)/Build.py \
    $(TREMOLITE)/Compile.py $(TREMOLITE)/Core.py $(TREMOLITE)/CreateMatch.py \
    $(TREMOLITE)/Main.py \
    $(TREMOLITE)/Name.py \
    $(TREMOLITE)/Parse.py $(TREMOLITE)/PatternWrapper.py \
    #
    #   Excludes:
    #       $(TREMOLITE)/LICENSE
    #       $(TREMOLITE)/Match.py
    #


TREMOLITE_2=../Tremolite/Tremolite_2

TREMOLITE_2_FILES = \
    $(TREMOLITE_2)/Core.py \
    $(TREMOLITE_2)/Main.py \
    $(TREMOLITE_2)/Parse.py $(TREMOLITE_2)/Parse1.py \
        $(TREMOLITE_2)/Pattern.py
    #
    #   Excludes:
    #       $(TREMOLITE_2)/Match.py


SARDONYX = ../Parser/Sardonyx

SARDONYX_FILES = \
    $(SARDONYX)/Boot.py

WORK_FILES = \
    Makefile

FILES = \
    $(AGATE_FILES) \
    $(BERYL_FILES) \
    $(CRYSTAL_FILES) \
    $(DIAMOND_FILES) \
    $(DRAVITE_FILES) \
    $(GEM_FILES) \
    $(IVORY_FILES) \
    $(JASPER_FILES) \
    $(LICENSE_FILES) \
    $(MARBLE_FILES) \
    $(MELANITE_FILES) \
    $(ONYX_FILES) \
    $(PEARL_FILES) \
    $(QUARTZ_FILES) \
    $(SAPPHIRE_FILES) \
    $(SARDONYX_FILES) \
    $(TOPAZ_FILES) \
    $(TREMOLITE_2_FILES) \
    $(TREMOLITE_FILES) \
    $(WORK_FILES)


all: clean files links


clean:
	rm -rf __pycache__
	rm -f *.old *.new *.pyc
	rm -f 2re.py 2sf.py 2sp.py 2sc.py
	rm -f 3re.py 3sf.py 3sp.py 3sc.py
	rm -f a.py ab.py ac.py ag.py
	rm -f ba.py bi.py bk.py bm.py bo.py
	rm -f ca.py ca2.py cd.py ce.py cr.py
	rm -f d.py dc.py de.py df.py dfo.py di.py dm.py dr.py dsh.py dst.py dt.py dw.py dy.py
	rm -f ef.py en.py ex.py
	rm -f files fo.py fs.py
	rm -f gcm.py gdc.py gdm.py gdo.py gga.py ggc.py gg4.py gh2.py gh3.py gh4.py ghe.py ghm.py gho.py
	rm -f   gi.py gl.py gq.py gr.py gse.py gsq.py
	rm -f h0p.py
	rm -f   h1p.py h1pa.py h1pc.py h1pe.py h1pes.py h1pf.py h1pi.py h1pm.py h1ps.py h1px.py
	rm -f     h1za.py h1zh.py h1zn.py h1zo.py
	rm -f   h2f.py h2p.py h2ps.py h2s.py h2s.py h2t.py h2w.py
	rm -f   h3e.py h3f.py h3p.py h3s.py h3t.py h3w.py
	rm -f   h4f.py h4s.py h4t.py h4w.py
	rm -f   hat.py hbe.py hby.py hca.py hcb.py hcc.py hcm.py hco.py hcr.py hcs.py hd.py hdh.py hdt.py hel.py
	rm -f   hk.py hkc.py hkd.py hkds.py hkf.py hkk.py hkkd.py hkm.py hkms.py hks.py hkt.py hi.py hl.py
	rm -f   hma.py hma1.py hma2.py hmc.py hmd.py hme.py hmf.py hmo.py hmx.py hmy.py hpr.py hpt.py hs.py
	rm -f   hto.py htr.py htt.py hu.py hv.py hw.py hx.py hy.py
	rm -f in.py im.py io.py iv.py
	rm -f j0p.py j1p.py jb.py jcr.py jma.py jmc.py jp.py
	rm -f l.txt lr1.txt lr2.txt
	rm -f m m1c.py m1ga.py m1gt.py m1m.py m1n.py
	rm -f   m2c.py m2m.py m3m.py
	rm -f   map.py mc.py md.py me.py mm.py
	rm -f o.py oc.py od.py oe.py om.py
	rm -f pa2.py pat.py path.py paw.py pca.py pcc.py pco.py pcr.py pcm.py
	rm -f   pel.py pf.py pj.py pk.py pkc.py pl.py pmo.py pn.py ps3.py
	rm -f q1p.py qc.py ql.py qma.py qmc.py qp.py
	rm -f rx.py
	rm -f sl.py so.py ssio.py sy.py
	rm -f t.java t0p.py t1.py t1p.py t2.py tb.py tcm.py th.py tcr.py tcr1.py tlp.txt
	rm -f   tma.py tma1.py tmc.py tmc1.py tn.py tp.py tp1.py tu.py tw.py tx.py
	rm -f xb.py xf.py
	rm -f vm.py
	rm -f ybd.py ybi.py ybq.py ycb.py ycr.py yd7.py yg.py yki.py ykn.py
	rm -f   ym.py yp.py yq.py yr.py ys.py yv.py yw.py yzc.py yzk.py yzr.py
	rm -f zcr.py zcs.py zd.py ze.py zg2.gpy zg2.py zg3.gpy zg3.py zg4.gpy zg4.py
	rm -f   zgn.gpy zgn.py zh.py zj1.py zj2.py zj3.py zj4.py zjtc.py
	rm -f   zm.py zo4.py zpa.py zps.py zpt.py zse.py zso.py zsq.py


files:
	echo $(FILES) >files.1.tmp
	tr ' ' '\n' <files.1.tmp >files.2.tmp
	mv files.2.tmp files


links:
	ln -s /usr/lib/python2.7/re.py                                              2re.py
	ln -s /usr/lib/python2.7/sre_compile.py                                     2sc.py
	ln -s /usr/lib/python2.7/sre_constants.py                                   2sf.py
	ln -s /usr/lib/python2.7/sre_parse.py                                       2sp.py
	ln -s /usr/lib/python3.5/re.py                                              3re.py
	ln -s /usr/lib/python3.5/sre_compile.py                                     3sc.py
	ln -s /usr/lib/python3.5/sre_constants.py                                   3sf.py
	ln -s /usr/lib/python3.5/sre_parse.py                                       3sp.py
	ln -s $(GEM)/All.py                                                         a.py
	ln -s $(GEM)/Absent.py                                                      ab.py
	ln -s $(GEM)/Ascii.py                                                       ac.py
	ln -s $(AGATE)/RUNME.py                                                     ag.py
	ln -s $(BERYL)/BerylAnswer.py                                               ba.py
	ln -s $(BERYL)/__init__.py                                                  bi.py
	ln -s $(BERYL)/Ask.py                                                       bk.py
	ln -s $(BERYL)/Main.py                                                      bm.py
	ln -s $(GEM)/Boot.py                                                        bo.py
	ln -s $(GEM)/Cache.py                                                       ca.py
	ln -s $(GEM)/Cache2.py                                                      ca2.py
	ln -s $(GEM)/Cadence.py                                                     cd.py
	ln -s $(GEM)/CatchException.py                                              ce.py
	ln -s $(GEM)/Core.py                                                        cr.py
	ln -s $(DIAMOND)/Development.py                                             d.py
	ln -s $(DIAMOND)/Core.py                                                    dc.py
	ln -s $(DRAVITE)/Euclid.py                                                  de.py
	ln -s $(DIAMOND)/Fibonacci.py                                               df.py
	ln -s $(GEM)/DelayedFileOutput.py                                           dfo.py
	ln -s $(DIAMOND)/Interval.py                                                di.py
	ln -s $(DIAMOND)/Main.py                                                    dm.py
	ln -s $(DRAVITE)/RSA_Example.py                                             dr.py
	ln -s $(DIAMOND)/Shared.py                                                  dsh.py
	ln -s $(DIAMOND)/Status.py                                                  dst.py
	ln -s $(DIAMOND)/Thread.py                                                  dt.py
	ln -s $(DIAMOND)/Chore.py                                                   dw.py
	ln -s $(DIAMOND)/LifeCycle.py                                               dy.py
	ln -s $(GEM)/ExecuteFile.py                                                 ef.py
	ln -s $(GEM)/ErrorNumber.py                                                 en.py
	ln -s $(GEM)/Exception.py                                                   ex.py
	ln -s $(GEM)/FileOutput.py                                                  fo.py
	ln -s $(GEM)/FileStatus.py                                                  fs.py
	ln -s $(GEM)/ContextManager.py                                              gcm.py
	ln -s $(GEM)/DumpCache.py                                                   gdc.py
	ln -s $(GEM)/DroveMany.py                                                   gdm.py
	ln -s $(GEM)/Codec.py                                                       gdo.py
	ln -s $(GEM)/Gaggle.py                                                      gga.py
	ln -s $(GEM)/GarbageCollection.py                                           ggc.py
	ln -s $(GEM)/GeneratedConjureQuadruple.py                                   gg4.py
	ln -s $(GEM)/Herd_2.py                                                      gh2.py
	ln -s $(GEM)/Herd_3.py                                                      gh3.py
	ln -s $(GEM)/Herd_4567.py                                                   gh4.py
	ln -s $(GEM)/Herd.py                                                        ghe.py
	ln -s $(GEM)/HerdMany.py                                                    ghm.py
	ln -s $(GEM)/Horde.py                                                       gho.py
	ln -s $(GEM)/Hailstone.py                                                   gi.py
	ln -s $(GEM)/Global.py                                                      gl.py
	ln -s $(GEM)/LiquidMap.py                                                   gq.py
	ln -s $(GEM)/Rabble.py                                                      gr.py
	ln -s $(GEM)/Series.py                                                      gse.py
	ln -s $(GEM)/Sequence.py                                                    gsq.py
	ln -s $(SAPPHIRE)/Parse.py                                                  h0p.py
	ln -s $(SAPPHIRE)/Parse1.py                                                 h1p.py
	ln -s $(SAPPHIRE)/Parse1Atom.py                                             h1pa.py
	ln -s $(SAPPHIRE)/Parse1Call.py                                             h1pc.py
	ln -s $(SAPPHIRE)/Parse1Expression.py                                       h1pe.py
	ln -s $(SAPPHIRE)/Parse1ExpressionStatement.py                              h1pes.py
	ln -s $(SAPPHIRE)/Parse1Function.py                                         h1pf.py
	ln -s $(SAPPHIRE)/Parse1Import.py                                           h1pi.py
	ln -s $(SAPPHIRE)/Parse1From.py                                             h1pm.py
	ln -s $(SAPPHIRE)/Parse1Simple.py                                           h1ps.py
	ln -s $(SAPPHIRE)/Parse1Complex.py                                          h1px.py
	ln -s $(SAPPHIRE)/Tokenize1Atom.py                                          h1za.py
	ln -s $(SAPPHIRE)/Tokenize1Header.py                                        h1zh.py
	ln -s $(SAPPHIRE)/Tokenize1Name.py                                          h1zn.py
	ln -s $(SAPPHIRE)/Tokenize1Operator.py                                      h1zo.py
	ln -s $(SAPPHIRE)/Parse2.py                                                 h2p.py
	ln -s $(SAPPHIRE)/Parse3.py                                                 h3p.py
	ln -s $(SAPPHIRE)/DualFrill.py                                              h2f.py
	ln -s $(SAPPHIRE)/PrefixedDualStatement.py                                  h2ps.py
	ln -s $(SAPPHIRE)/DualStatement.py                                          h2s.py
	ln -s $(SAPPHIRE)/DualToken.py                                              h2t.py
	ln -s $(SAPPHIRE)/DualTwig.py                                               h2w.py
	ln -s $(SAPPHIRE)/TernaryExpression.py                                      h3e.py
	ln -s $(SAPPHIRE)/TripleFrill.py                                            h3f.py
	ln -s $(SAPPHIRE)/TripleStatement.py                                        h3s.py
	ln -s $(SAPPHIRE)/TripleToken.py                                            h3t.py
	ln -s $(SAPPHIRE)/TripleTwig.py                                             h3w.py
	ln -s $(SAPPHIRE)/QuadrupleFrill.py                                         h4f.py
	ln -s $(SAPPHIRE)/QuadrupleStatement.py                                     h4s.py
	ln -s $(SAPPHIRE)/QuadrupleToken.py                                         h4t.py
	ln -s $(SAPPHIRE)/QuadrupleTwig.py                                          h4w.py
	ln -s $(SAPPHIRE)/Atom.py                                                   hat.py
	ln -s $(SAPPHIRE)/BinaryExpression.py                                       hbe.py
	ln -s $(SAPPHIRE)/BuildSymbolTable.py                                       hby.py
	ln -s $(SAPPHIRE)/Cache.py                                                  hca.py
	ln -s $(SAPPHIRE)/Combine.py                                                hcb.py
	ln -s $(SAPPHIRE)/CreateMeta.py                                             hcc.py
	ln -s $(SAPPHIRE)/Comment.py                                                hcm.py
	ln -s $(SAPPHIRE)/ClassOrder.py                                             hco.py
	ln -s $(SAPPHIRE)/CallStatement.py                                          hcs.py
	ln -s $(SAPPHIRE)/Core.py                                                   hcr.py
	ln -s $(SAPPHIRE)/Development.py                                            hd.py
	ln -s $(SAPPHIRE)/DefinitionHeader.py                                       hdh.py
	ln -s $(SAPPHIRE)/DumpToken.py                                              hdt.py
	ln -s $(SAPPHIRE)/Elemental.py                                              hel.py
	ln -s $(SAPPHIRE)/BookcaseExpression.py                                     hk.py
	ln -s $(SAPPHIRE)/TokenCache.py                                             hkc.py
	ln -s $(SAPPHIRE)/BookcaseDualExpression.py                                 hkd.py
	ln -s $(SAPPHIRE)/BookcaseDualStatement.py                                  hkds.py
	ln -s $(SAPPHIRE)/BookcaseManyFrill.py                                      hkf.py
	ln -s $(SAPPHIRE)/BookcaseKeywordStatement.py                               hkk.py
	ln -s $(SAPPHIRE)/BookcaseKeywordDualStatement.py                           hkkd.py
	ln -s $(SAPPHIRE)/BookcaseManyExpression.py                                 hkm.py
	ln -s $(SAPPHIRE)/BookcaseManyStatement.py                                  hkms.py
	ln -s $(SAPPHIRE)/BookcaseStatement.py                                      hks.py
	ln -s $(SAPPHIRE)/BookcaseTriple.py                                         hkt.py
	ln -s $(SAPPHIRE)/Indentation.py                                            hi.py
	ln -s $(SAPPHIRE)/LineMarker.py                                             hl.py
	ln -s $(SAPPHIRE)/Main.py                                                   hma.py
	ln -s ../bin/.pyxie/hma.py                                                  hma1.py
	ln -s ../bin/.pyxie/hma2.py                                                 hma2.py
	ln -s $(SAPPHIRE)/Match.py                                                  hmc.py
	ln -s $(SAPPHIRE)/MosiacDefinition.py                                       hmd.py
	ln -s $(SAPPHIRE)/MemberExpression.py                                       hme.py
	ln -s $(SAPPHIRE)/ManyFrill.py                                              hmf.py
	ln -s $(SAPPHIRE)/Method.py                                                 hmo.py
	ln -s $(SAPPHIRE)/ManyExpression.py                                         hmx.py
	ln -s $(SAPPHIRE)/MosiacSymbol.py                                           hmy.py
	ln -s $(SAPPHIRE)/Priority.py                                               hpr.py
	ln -s $(SAPPHIRE)/Pattern.py                                                hpt.py
	ln -s $(SAPPHIRE)/Suite.py                                                  hs.py
	ln -s $(SAPPHIRE)/TupleOfExpression.py                                      hto.py
	ln -s $(SAPPHIRE)/Tree.py                                                   htr.py
	ln -s $(SAPPHIRE)/TokenTuple.py                                             htt.py
	ln -s $(SAPPHIRE)/UnaryExpression.py                                        hu.py
	ln -s $(SAPPHIRE)/Variable.py                                               hv.py
	ln -s $(SAPPHIRE)/Whitespace.py                                             hw.py
	ln -s $(SAPPHIRE)/PostfixExpression.py                                      hx.py
	ln -s $(SAPPHIRE)/SymbolTable.py                                            hy.py
	ln -s $(GEM)/__init__.py                                                    in.py
	ln -s $(GEM)/Import.py                                                      im.py
	ln -s $(IVORY)/Main.py                                                      iv.py
	ln -s $(GEM)/IO.py                                                          io.py
	ln -s $(JASPER)/Parse.py                                                    j0p.py
	ln -s $(JASPER)/Parse1.py                                                   j1p.py
	ln -s ../Old/Junk/Boot.py                                                   jb.py
	ln -s $(JASPER)/Core.py                                                     jcr.py
	ln -s $(JASPER)/Main.py                                                     jma.py
	ln -s $(JASPER)/Match.py                                                    jmc.py
	ln -s $(JASPER)/Pattern.py                                                  jp.py
	ln -s log.txt                                                               l.txt
	ln -s ../PPK/OtherLicenses/README.txt                                       lr1.txt
	ln -s ../Tremolite/OtherLicenses/README.txt                                 lr2.txt
	ln -s Makefile                                                              m
	ln -s $(MARBLE)/Core.py                                                     m1c.py
	ln -s $(MARBLE)/GenerateAscii.py                                            m1ga.py
	ln -s $(MARBLE)/GenerateTestPortrayString.py                                m1gt.py
	ln -s $(MARBLE)/Main.py                                                     m1m.py
	ln -s $(MARBLE)/NestedConjure.py                                            m1n.py
	ln -s $(MELANITE)/Core.py                                                   m2c.py
	ln -s $(MELANITE)/Main.py                                                   m2m.py
	ln -s $(GEM)/Map.py                                                         map.py
	ln -s $(MELANITE)/Child.py                                                  mc.py
	ln -s $(MELANITE)/Development.py                                            md.py
	ln -s $(GEM)/Method.py                                                      me.py
	ln -s $(MELANITE)/Multiprocessing.py                                        mm.py
	ln -s $(GEM)/Output.py                                                      o.py
	ln -s $(ONYX)/Core.py                                                       oc.py
	ln -s $(ONYX)/Development.py                                                od.py
	ln -s $(ONYX)/ElasticSearch.py                                              oe.py
	ln -s $(ONYX)/Main.py                                                       om.py
	ln -s $(GEM)/Path2.py                                                       pa2.py
	ln -s $(PEARL)/Atom.py                                                      pat.py
	ln -s $(GEM)/Path.py                                                        path.py
	ln -s $(PEARL)/ActionWord.py                                                paw.py
	ln -s $(PEARL)/Cache.py                                                     pca.py
	ln -s $(PEARL)/CreateMeta.py                                                pcc.py
	ln -s $(PEARL)/Comment.py                                                   pcm.py
	ln -s $(PEARL)/ClassOrder.py                                                pco.py
	ln -s $(PEARL)/Core.py                                                      pcr.py
	ln -s $(PEARL)/Elemental.py                                                 pel.py
	ln -s $(PEARL)/Tokenizer.py                                                 pf.py
	ln -s $(PEARL)/ConjureTreeComment.py                                        pj.py
	ln -s $(PEARL)/Token.py                                                     pk.py
	ln -s $(PEARL)/TokenCache.py                                                pkc.py
	ln -s $(PEARL)/Line.py                                                      pl.py
	ln -s $(PEARL)/Method.py                                                    pmo.py
	ln -s $(PEARL)/Nub.py                                                       pn.py
	ln -s ../Old/Junk/PortrayString_3.py                                        ps3.py
	ln -s $(QUARTZ)/Parse1.py                                                   q1p.py
	ln -s $(QUARTZ)/Core.py                                                     qc.py
	ln -s $(QUARTZ)/Line.py                                                     ql.py
	ln -s $(QUARTZ)/Main.py                                                     qma.py
	ln -s $(QUARTZ)/Match.py                                                    qmc.py
	ln -s $(QUARTZ)/Pattern.py                                                  qp.py
	ln -s $(GEM)/RegularExpression.py                                           rx.py
	ln -s $(GEM)/Sleep.py                                                       sl.py
	ln -s $(GEM)/StringOutput.py                                                so.py
	ln -s $(GEM)/SimpleStringIO.py                                              ssio.py
	ln -s $(GEM)/System.py                                                      sy.py
	ln -s test.java                                                             t.java
	ln -s $(TREMOLITE_2)/Parse.py                                               t0p.py
	ln -s test.py                                                               t1.py
	ln -s $(TREMOLITE_2)/Parse1.py                                              t1p.py
	ln -s test2.py                                                              t2.py
	ln -s $(GEM)/Traceback.py                                                   tb.py
	ln -s $(TREMOLITE)/CreateMatch.py                                           tcm.py
	ln -s $(TREMOLITE)/Core.py                                                  tcr.py
	ln -s $(TREMOLITE_2)/Core.py                                                tcr1.py
	ln -s $(GEM)/Thread.py                                                      th.py
	ln -s ../Tremolite/OtherLicenses/LicenseTemplate.txt                        tlp.txt
	ln -s $(TREMOLITE_2)/Main.py                                                tma.py
	ln -s $(TREMOLITE)/Main.py                                                  tma1.py
	ln -s $(TREMOLITE_2)/Match.py                                               tmc.py
	ln -s $(TREMOLITE)/Match.py                                                 tmc1.py
	ln -s $(TREMOLITE)/Name.py                                                  tn.py
	ln -s $(TREMOLITE_2)/Pattern.py                                             tp.py
	ln -s $(TREMOLITE)/Parse.py                                                 tp1.py
	ln -s $(TREMOLITE)/Build.py                                                 tu.py
	ln -s $(TREMOLITE)/PatternWrapper.py                                        tw.py
	ln -s $(TREMOLITE)/Compile.py                                               tx.py
	ln -s $(DRAVITE)/Main.py                                                    vm.py
	ln -s $(SARDONYX)/Boot.py                                                   xb.py
	ln -s $(SAPPHIRE)/Transform.py                                              xf.py
	ln -s $(CRYSTAL)/Board.py                                                   ybd.py
	ln -s $(CRYSTAL)/ChessBishop.py                                             ybi.py
	ln -s $(CRYSTAL)/BlankSquare.py                                             ybq.py
	ln -s $(CRYSTAL)/CardRoot.py                                                ycb.py
	ln -s $(CRYSTAL)/Core.py                                                    ycr.py
	ln -s $(CRYSTAL)/Deck_7.py                                                  yd7.py
	ln -s $(CRYSTAL)/Game.py                                                    yg.py
	ln -s $(CRYSTAL)/ChessKing.py                                               yki.py
	ln -s $(CRYSTAL)/ChessKnight.py                                             ykn.py
	ln -s $(CRYSTAL)/Main.py                                                    ym.py
	ln -s $(CRYSTAL)/Player.py                                                  yp.py
	ln -s $(CRYSTAL)/Square.py                                                  yq.py
	ln -s $(CRYSTAL)/ChessRook.py                                               yr.py
	ln -s $(GEM)/PortrayString.py                                               ys.py
	ln -s $(CRYSTAL)/VoidSquare.py                                              yv.py
	ln -s $(CRYSTAL)/ChessPawn.py                                               yw.py
	ln -s $(CRYSTAL)/FrozenChessCard.py                                         yzc.py
	ln -s $(CRYSTAL)/FrozenCardRoot.py                                          yzr.py
	ln -s $(TOPAZ)/Core.py                                                      zcr.py
	ln -s $(TOPAZ)/CacheSupport.py                                              zcs.py
	ln -s $(TOPAZ)/Drove.py                                                     zd.py
	ln -s $(TOPAZ)/ExceptionChain.py                                            ze.py
	ln -s $(TOPAZ)/GeneratedConjureDual.gpy                                     zg2.gpy
	ln -s $(TOPAZ)/GeneratedConjureDual.py                                      zg2.py
	ln -s $(TOPAZ)/GeneratedConjureTriple.gpy                                   zg3.gpy
	ln -s $(TOPAZ)/GeneratedConjureTriple.py                                    zg3.py
	ln -s $(TOPAZ)/GeneratedConjureQuadruple.gpy                                zg4.gpy
	ln -s $(TOPAZ)/GeneratedConjureQuadruple.py                                 zg4.py
	ln -s $(TOPAZ)/GeneratedNew.gpy                                             zgn.gpy
	ln -s $(TOPAZ)/GeneratedNew.py                                              zgn.py
	ln -s $(TOPAZ)/Herd.py                                                      zh.py
	ln -s $(TOPAZ)/ConjureSingle.py                                             zj1.py
	ln -s $(TOPAZ)/ConjureDual.py                                               zj2.py
	ln -s $(TOPAZ)/ConjureTriple.py                                             zj3.py
	ln -s $(TOPAZ)/ConjureQuadruple.py                                          zj4.py
	ln -s $(TOPAZ)/ConjureTreeComment.py                                        zjtc.py
	ln -s $(TOPAZ)/Main.py                                                      zm.py
	ln -s $(TOPAZ)/OldConjureQuadruple.py                                       zo4.py
	ln -s $(TOPAZ)/Path.py                                                      zpa.py
	ln -s $(TOPAZ)/PortrayString.py                                             zps.py
	ln -s $(TOPAZ)/Pattern.py                                                   zpt.py
	ln -s $(TOPAZ)/Series.py                                                    zse.py
	ln -s $(TOPAZ)/StringOutput.py                                              zso.py
	ln -s $(TOPAZ)/Sequence.py                                                  zsq.py


wc:
	#
	#  Excludes $(AGATE_FILES)
	#
	wc -l \
        $(BERYL_FILES) \
        $(CRYSTAL_FILES) \
        $(DIAMOND_FILES) \
        $(DRAVITE_FILES) \
        $(GEM_FILES) \
        $(IVORY_FILES) \
        $(JASPER_FILES) \
        $(LICENSE_FILES) \
        $(MARBLE_FILES) \
        $(MELANITE_FILES) \
        $(ONYX_FILES) \
        $(QUARTZ_FILES) \
        $(SAPPHIRE_FILES) \
        $(SARDONYX_FILES) \
        $(TOPAZ_FILES) \
        $(TREMOLITE_FILES) \
        $(TREMOLITE_2_FILES) \
        $(WORK_FILES)

test:
	cat \
        $(BERYL_FILES) \
        $(CRYSTAL_FILES) \
        $(DIAMOND_FILES) \
        $(DRAVITE_FILES) \
        $(GEM_FILES) \
        $(IVORY_FILES) \
        $(JASPER_FILES) \
        $(MELANITE_FILES) \
        $(ONYX_FILES) \
        $(PEARL_FILES) \
        $(QUARTZ_FILES) \
        $(SAPPHIRE_FILES) \
        $(SARDONYX_FILES) \
        $(TOPAZ_FILES) \
        $(TREMOLITE_FILES) \
        $(TREMOLITE_2_FILES) \
            >test.py
	bash run.sh
