#
#   Copyright (c) 2017-2018 Joy Diamond.  All rights reserved.
#
Agate = ../Old/Agate

Agate_Files = \
    $(Agate)/RUNME.py


Beryl = ../Old/Beryl

Beryl_Files = \
    $(Beryl)/__init__.py \
    $(Beryl)/Ask.py \
    $(Beryl)/BerylAnswer.py \
    $(Beryl)/Main.py \


Capital = ../Capital/Capital

Capital_Files = \
    $(Capital)/__init__.py \
    $(Capital)/Absent.py $(Capital)/All.py $(Capital)/Ascii.py \
    $(Capital)/Boot.py \
    $(Capital)/Cache.py $(Capital)/Cache2.py $(Capital)/Cadence.py $(Capital)/Codec.py $(Capital)/ContextManager.py \
        $(Capital)/Core.py $(Capital)/CatchException.py \
    $(Capital)/DelayedFileOutput.py $(Capital)/DroveMany.py $(Capital)/DumpCache.py \
    $(Capital)/ErrorNumber.py $(Capital)/Exception.py $(Capital)/ExecuteFile.py \
    $(Capital)/FileOutput.py $(Capital)/FileStatus.py \
    $(Capital)/Gaggle.py $(Capital)/GarbageCollection.py $(Capital)/Global.py \
    $(Capital)/Hailstone.py $(Capital)/Herd.py $(Capital)/Herd_2.py $(Capital)/Herd_3.py $(Capital)/Herd_4567.py \
        $(Capital)/HerdMany.py $(Capital)/Horde.py \
    $(Capital)/Import.py $(Capital)/IO.py \
    $(Capital)/LiquidMap.py \
    $(Capital)/Map.py $(Capital)/Method.py \
    $(Capital)/Output.py \
    $(Capital)/Path.py $(Capital)/Path2.py $(Capital)/PortrayString.py \
    $(Capital)/Rabble.py $(Capital)/RegularExpression.py \
    $(Capital)/Series.py $(Capital)/Sequence.py $(Capital)/SimpleStringIO.py $(Capital)/Sleep.py \
        $(Capital)/StringOutput.py $(Capital)/System.py \
    $(Capital)/Traceback.py $(Capital)/Thread.py \

Capital_Generated = \
    $(Capital)/GeneratedConjureQuadruple.py \


Chess5x2 = ../Other/Chess5x2

Chess5x2_Files = \
    $(Chess5x2)/__init__.py \
    $(Chess5x2)/Board.py $(Chess5x2)/BlankSquare.py \
    $(Chess5x2)/CardRoot.py $(Chess5x2)/ChessBishop.py $(Chess5x2)/ChessKing.py $(Chess5x2)/ChessKnight.py \
        $(Chess5x2)/ChessPawn.py $(Chess5x2)/ChessRook.py $(Chess5x2)/Core.py \
    $(Chess5x2)/Deck_7.py \
    $(Chess5x2)/FrozenChessCard.py $(Chess5x2)/FrozenCardRoot.py \
    $(Chess5x2)/Game.py \
    $(Chess5x2)/Main.py \
    $(Chess5x2)/Player.py \
    $(Chess5x2)/Square.py \
    $(Chess5x2)/VoidSquare.py \


CodeGenerator = ../Other/CodeGenerator

CodeGenerator_Files = \
    $(CodeGenerator)/Core.py \
    $(CodeGenerator)/GenerateAscii.py \
    $(CodeGenerator)/GenerateTestPortrayString.py \
    $(CodeGenerator)/NestedConjure.py \
    $(CodeGenerator)/Main.py \


CoreParser = ../Parser/CoreParser

CoreParser_Files = \
    $(CoreParser)/ActionWord.py $(CoreParser)/Atom.py \
	$(CoreParser)/BookcaseCoupleTwig.py $(CoreParser)/BookcaseDualTwig.py \
    $(CoreParser)/Cache.py $(CoreParser)/ClassOrder.py $(CoreParser)/Core.py $(CoreParser)/CrystalComment.py \
        $(CoreParser)/CrystalIndentation.py $(CoreParser)/CreateMeta.py \
    $(CoreParser)/DualFrill.py $(CoreParser)/DualTwig.py $(CoreParser)/DumpToken.py \
    $(CoreParser)/Elemental.py \
    $(CoreParser)/EmptyLine.py \
    $(CoreParser)/LineMarker.py \
    $(CoreParser)/Method.py \
    $(CoreParser)/Nub.py \
    $(CoreParser)/ParserToken.py $(CoreParser)/ParserTrunk.py \
    $(CoreParser)/TokenCache.py $(CoreParser)/Tokenizer.py $(CoreParser)/TestTree.py $(CoreParser)/TripleFrill.py \
        $(CoreParser)/TripleTwig.py \


JavaParser = ../Parser/Mothballed/JavaParser

JavaParser_Files = \
    $(JavaParser)/Core.py \
    $(JavaParser)/Main.py \
    $(JavaParser)/Parse.py $(JavaParser)/Parse1.py $(JavaParser)/Pattern.py \

JavaParser_Generated = \
    $(JavaParser)/Match.py \


LearningPython = ../Other/LearningPython

LearningPython_Files = \
    $(LearningPython)/Main.py \


License_Files = \
    ../PPK/OtherLicenses/README.txt \
    ../Tremolite/OtherLicenses/README.txt \


LockFree = ../Other/LockFree

LockFree_Files = \
    $(LockFree)/__init__.py \
    $(LockFree)/Chore.py $(LockFree)/Core.py \
    $(LockFree)/Development.py \
    $(LockFree)/Fibonacci.py \
    $(LockFree)/Interval.py \
    $(LockFree)/LifeCycle.py \
    $(LockFree)/Main.py \
    $(LockFree)/Shared.py $(LockFree)/Status.py \
    $(LockFree)/Thread.py \


KeyExample = ../PPK/KeyExample

KeyExample_Files = \
    $(KeyExample)/Euclid.py \
    $(KeyExample)/__init__.py \
    $(KeyExample)/Main.py \
    $(KeyExample)/RSA_Example.py \


MultiProcessingExample = ../Other/MultiProcessingExample

MultiProcessingExample_Files = \
    $(MultiProcessingExample)/Child.py \
    $(MultiProcessingExample)/Core.py \
    $(MultiProcessingExample)/Development.py \
    $(MultiProcessingExample)/Main.py \
    $(MultiProcessingExample)/Multiprocessing.py \


PythonParser = ../Parser/PythonParser

PythonParser_Files = \
    $(PythonParser)/Atom.py \
    $(PythonParser)/BinaryExpression.py $(PythonParser)/BookcaseDualExpression.py \
        $(PythonParser)/BookcaseDualStatement.py $(PythonParser)/BookcaseExpression.py \
        $(PythonParser)/BookcaseKeywordStatement.py $(PythonParser)/BookcaseKeywordDualStatement.py \
        $(PythonParser)/BookcaseManyExpression.py $(PythonParser)/BookcaseManyFrill.py \
        $(PythonParser)/BookcaseManyStatement.py $(PythonParser)/BookcaseStatement.py \
        $(PythonParser)/BookcaseTriple.py $(PythonParser)/BuildSymbolTable.py \
    $(PythonParser)/Cache.py $(PythonParser)/CallStatement.py $(PythonParser)/ClassOrder.py \
        $(PythonParser)/Combine.py $(PythonParser)/Core.py $(PythonParser)/CreateMeta.py \
    $(PythonParser)/DefinitionHeader.py $(PythonParser)/Development.py $(PythonParser)/DualStatement.py \
        $(PythonParser)/DualToken.py \
    $(PythonParser)/Elemental.py \
    $(PythonParser)/Main.py $(PythonParser)/ManyExpression.py $(PythonParser)/ManyFrill.py \
        $(PythonParser)/MemberExpression.py $(PythonParser)/Method.py $(PythonParser)/MosiacDefinition.py \
        $(PythonParser)/MosiacSymbol.py \
    $(PythonParser)/Parse.py \
        $(PythonParser)/Parse1.py $(PythonParser)/Parse1Atom.py $(PythonParser)/Tokenize1Header.py \
        $(PythonParser)/Parse1Call.py $(PythonParser)/Parse1Complex.py $(PythonParser)/Parse1Expression.py \
        $(PythonParser)/Parse1ExpressionStatement.py $(PythonParser)/Parse1From.py \
        $(PythonParser)/Parse1Function.py $(PythonParser)/Parse1Import.py $(PythonParser)/Parse1Simple.py \
        $(PythonParser)/Parse3.py $(PythonParser)/PostfixExpression.py $(PythonParser)/PrefixedDualStatement.py \
        $(PythonParser)/Priority.py \
    $(PythonParser)/Pattern.py \
    $(PythonParser)/QuadrupleFrill.py $(PythonParser)/QuadrupleStatement.py $(PythonParser)/QuadrupleToken.py \
        $(PythonParser)/QuadrupleTwig.py \
    $(PythonParser)/Suite.py $(PythonParser)/SymbolTable.py \
    $(PythonParser)/TernaryExpression.py $(PythonParser)/TokenCache.py $(PythonParser)/TokenTuple.py \
        $(PythonParser)/Tokenize1Atom.py $(PythonParser)/Tokenize1Name.py \
        $(PythonParser)/Tokenize1Operator.py $(PythonParser)/TripleStatement.py \
        $(PythonParser)/TripleToken.py \
        $(PythonParser)/TupleOfExpression.py \
    $(PythonParser)/UnaryExpression.py \
    $(PythonParser)/Whitespace.py \
    $(PythonParser)/Transform.py \
    $(PythonParser)/Variable.py \

PythonParser_Generated = \
    $(PythonParser)/Match.py \


Remedy = ../ErrorCorrecting/Remedy

Remedy_Files = \
    $(Remedy)/MockSolidStateDevice.py \
    $(Remedy)/Main.py \
    $(Remedy)/ReedSolomon.py


Restructure = ../Tremolite/Restructure

Restructure_Files = \
    $(Restructure)/Build.py \
    $(Restructure)/Core.py $(Restructure)/CreateMatch.py \
    $(Restructure)/Main.py \
    $(Restructure)/Name.py \

Restructure_Assets = \
    ../Tremolite/OtherLicenses/LicenseTemplate.txt \

Restructure_Generated = \
    $(Restructure)/Match.py \


Rex = ../Tremolite/Rex

Rex_Files = \
    $(Rex)/Compile.py $(Rex)/Core.py \
    $(Rex)/PatternWrapper.py $(Rex)/Parse.py \


Rubber = ../Other/Mothballed/Rubber

Rubber_Files = \
    $(Rubber)/__init__.py \
    $(Rubber)/Core.py \
    $(Rubber)/Development.py \
    $(Rubber)/ElasticSearch.py \
    $(Rubber)/Main.py \


SinglePythonFileBoot = ../Parser/Assets

SinglePythonFileBoot_Files = \
    $(SinglePythonFileBoot)/SinglePythonFileBoot.py \


SqlParser = ../Parser/Mothballed/SqlParser

SqlParser_Files = \
    $(SqlParser)/Comment.py $(SqlParser)/Core.py $(SqlParser)/ConjureTreeComment.py \
    $(SqlParser)/Line.py \
    $(SqlParser)/Main.py \
    $(SqlParser)/Parse1.py $(SqlParser)/Pattern.py \
    $(SqlParser)/Statement.py \

SqlParser_Generated = \
    $(SqlParser)/Match.py \


TremoliteParser = ../Tremolite/TremoliteParser

TremoliteParser_Files = \
    $(TremoliteParser)/Core.py \
    $(TremoliteParser)/Development.py \
    $(TremoliteParser)/Elemental.py \
    $(TremoliteParser)/Main.py \
    $(TremoliteParser)/Parse.py $(TremoliteParser)/Parse1.py $(TremoliteParser)/Pattern.py \
    $(TremoliteParser)/Statement.py \

TremoliteParser_Generated = \
    $(TremoliteParser)/Match.py \


UnitTest = ../UnitTest/UnitTest

UnitTest_Files = \
    $(UnitTest)/CacheSupport.py $(UnitTest)/ConjureDual.py $(UnitTest)/ConjureSingle.py \
        $(UnitTest)/ConjureQuadruple.py $(UnitTest)/ConjureTriple.py $(UnitTest)/ConjureTreeComment.py \
        $(UnitTest)/Core.py \
    $(UnitTest)/Drove.py \
    $(UnitTest)/ExceptionChain.py \
    $(UnitTest)/Herd.py \
    $(UnitTest)/Main.py \
    $(UnitTest)/Path.py $(UnitTest)/Pattern.py $(UnitTest)/PortrayString.py \
    $(UnitTest)/Sequence.py $(UnitTest)/Series.py $(UnitTest)/StringOutput.py \

UnitTest_Generated = \
    $(UnitTest)/GeneratedConjureDual.py $(UnitTest)/GeneratedConjureQuadruple.py \
        $(UnitTest)/GeneratedConjureTriple.py $(UnitTest)/GeneratedNew.py \
    $(UnitTest)/OldConjureQuadruple.py \


Work_Files = \
    Makefile \


Files = \
    $(Agate_Files) \
    $(Beryl_Files) \
    $(Capital_Generated) $(Capital_Files) \
    $(Chess5x2_Files) \
    $(CodeGenerator_Files) \
    $(CoreParser_Files) \
    $(JavaParser_Generated) $(JavaParser_Files) \
    $(KeyExample_Files) \
    $(LearningPython_Files) \
    $(License_Files) \
    $(LockFree_Files) \
    $(MultiProcessingExample_Files) \
    $(PythonParser_Generated) $(PythonParser_Files) \
    $(Remedy_Files) \
    $(Restructure_Assets) $(Restructure_Generated) $(Restructure_Files) \
    $(Rex_Files) \
    $(Rubber_Files) \
    $(SinglePythonFileBoot_Files) \
    $(SqlParser_Generated) $(SqlParser_Files) \
    $(TremoliteParser_Generated) $(TremoliteParser_Files) \
    $(UnitTest_Generated) $(UnitTest_Files) \
    $(Work_Files) \


all: clean files links


clean:
	rm -f 2re.py 2sf.py 2sp.py 2sc.py
	rm -f 3re.py 3sf.py 3sp.py 3sc.py
	rm -f a.py ab.py ac.py ag.py
	rm -f ba.py bi.py bk.py bm.py bo.py
	rm -f ca.py ca2.py cd.py ce.py cr.py
	rm -f dfo.py
	rm -f ef.py en.py erk.py erm.py ers.py ex.py
	rm -f files f.py fc.py ff.py dfo.py fi.py fm.py fo.py fs.py fsh.py fst.py ft.py fw.py fy.py
	rm -f g1c.py g1ga.py g1gt.py g1m.py g1n.py
	rm -f   gcm.py gdc.py gdm.py gdo.py gga.py ggc.py gg4.py gh2.py gh3.py gh4.py ghe.py ghm.py gho.py
	rm -f   gi.py gl.py gq.py gr.py gse.py gsq.py
	rm -f h0p.py
	rm -f   h1p.py h1pa.py h1pc.py h1pe.py h1pes.py h1pf.py h1pi.py h1pm.py h1ps.py h1px.py
	rm -f     h1za.py h1zh.py h1zn.py h1zo.py
	rm -f   h2ps.py h2s.py h2s.py h2t.py
	rm -f   h3e.py h3p.py h3s.py h3t.py
	rm -f   h4f.py h4s.py h4t.py h4w.py
	rm -f   hat.py hbe.py hby.py hca.py hcb.py hcc.py hco.py hcr.py hcs.py hd.py hdh.py hel.py
	rm -f   hk.py hkc.py hkd.py hkds.py hkf.py hkk.py hkkd.py hkm.py hkms.py hks.py hkt.py
	rm -f   hma.py hma1.py hma2.py hmc.py hmd.py hme.py hmf.py hmo.py hmx.py hmy.py hpr.py hpt.py hs.py
	rm -f   hto.py htt.py hu.py hv.py hwy.py hx.py hy.py
	rm -f in.py im.py io.py
	rm -f j0p.py j1p.py jb.py jcr.py jma.py jmc.py jp.py
	rm -f ke.py km.py kr.py
	rm -f l.txt lpm.py lr1.txt
	rm -f m
	rm -f   m2ch.py m2cr.py m2d.py m2m.py m2ma.py m3m.py
	rm -f   map.py me.py
	rm -f o.py
	rm -f p2f.py p2w.py pa2.py p3f.py p3w.py pat.py path.py paw.py pca.py pcc.py pco.py pcr.py
	rm -f   pdt.py pel.py pem.py pf.py pk2.py pk2c.py pkc.py
	rm -f   pl.py pm.py pn.py ps3.py ptt.py pyc.py pyi.py pyk.py pyt.py
	rm -f q1p.py qcm.py qcr.py qj.py ql.py qma.py qmc.py qp.py qs.py
	rm -f r0p.py r1p.py rcm.py rcr.py rcr2.py rd.py re.py rel.py rlp.txt rlr.txt
	rm -f   rma.py rma2.py rmc.py rmc2.py rn.py rp.py rs.py ru.py rxc.py rxcr.py rxp.py rxw.py
	rm -f sl.py so.py ssio.py sy.py
	rm -f t.java t1.py t2.py tb.py th.py
	rm -f uc.py ud.py ue.py um.py
	rm -f xb.py xf.py
	rm -f ybd.py ybi.py ybq.py ycb.py ycr.py yd7.py yg.py yki.py ykn.py
	rm -f   ym.py yp.py yq.py yr.py ys.py yv.py yw.py yzc.py yzk.py yzr.py
	rm -f zcr.py zcs.py zd.py ze.py zg2.gpy zg2.py zg3.gpy zg3.py zg4.gpy zg4.py
	rm -f   zgn.gpy zgn.py zh.py zj1.py zj2.py zj3.py zj4.py zjtc.py
	rm -f   zm.py zo4.py zpa.py zpt.py zse.py zso.py zsq.py zys.py
	find .. -name __pycache__ >files.1.tmp; xargs rm -rf <files.1.tmp
	find .. \( -name '*.py[co]' -o -name '*.old' -o -name '*.tmp' \) -print >files.1.tmp; xargs rm -f <files.1.tmp
	rm -f files.1.tmp


files:
	echo $(Files) >files.1.tmp
	tr ' ' '\n' <files.1.tmp >files.2.tmp
	mv files.2.tmp files


links:
	ln -s /usr/lib/python2.7/re.py                                              2re.py
	ln -s /usr/lib/python2.7/sre_compile.py                                     2sc.py
	ln -s /usr/lib/python2.7/sre_constants.py                                   2sf.py
	ln -s /usr/lib/python2.7/sre_parse.py                                       2sp.py
	ln -s /usr/lib/python3.5/re.py                                              3re.py
	ln -s /usr/lib/python3.5/sre_compile.py                                     3sc.py
	ln -s /usr/lib/python3.5/sre_constants.py                                   3sf.py
	ln -s /usr/lib/python3.5/sre_parse.py                                       3sp.py
	ln -s $(Capital)/All.py                                                     a.py
	ln -s $(Capital)/Absent.py                                                  ab.py
	ln -s $(Capital)/Ascii.py                                                   ac.py
	ln -s $(Agate)/RUNME.py                                                     ag.py
	ln -s $(Beryl)/BerylAnswer.py                                               ba.py
	ln -s $(Beryl)/__init__.py                                                  bi.py
	ln -s $(Beryl)/Ask.py                                                       bk.py
	ln -s $(Beryl)/Main.py                                                      bm.py
	ln -s $(Capital)/Boot.py                                                    bo.py
	ln -s $(Capital)/Cache.py                                                   ca.py
	ln -s $(Capital)/Cache2.py                                                  ca2.py
	ln -s $(Capital)/Cadence.py                                                 cd.py
	ln -s $(Capital)/CatchException.py                                          ce.py
	ln -s $(Capital)/Core.py                                                    cr.py
	ln -s $(Capital)/DelayedFileOutput.py                                       dfo.py
	ln -s $(Capital)/ExecuteFile.py                                             ef.py
	ln -s $(Capital)/ErrorNumber.py                                             en.py
	ln -s $(Remedy)/MockSolidStateDevice.py                                     erk.py
	ln -s $(Remedy)/Main.py                                                     erm.py
	ln -s $(Remedy)/ReedSolomon.py                                              ers.py
	ln -s $(Capital)/Exception.py                                               ex.py
	ln -s $(LockFree)/Development.py                                            f.py
	ln -s $(LockFree)/Core.py                                                   fc.py
	ln -s $(LockFree)/Fibonacci.py                                              ff.py
	ln -s $(LockFree)/Interval.py                                               fi.py
	ln -s $(LockFree)/Main.py                                                   fm.py
	ln -s $(Capital)/FileOutput.py                                              fo.py
	ln -s $(Capital)/FileStatus.py                                              fs.py
	ln -s $(LockFree)/Shared.py                                                 fsh.py
	ln -s $(LockFree)/Status.py                                                 fst.py
	ln -s $(LockFree)/Thread.py                                                 ft.py
	ln -s $(LockFree)/Chore.py                                                  fw.py
	ln -s $(LockFree)/LifeCycle.py                                              fy.py
	ln -s $(Capital)/ContextManager.py                                          gcm.py
	ln -s $(Capital)/DumpCache.py                                               gdc.py
	ln -s $(Capital)/DroveMany.py                                               gdm.py
	ln -s $(Capital)/Codec.py                                                   gdo.py
	ln -s $(Capital)/Gaggle.py                                                  gga.py
	ln -s $(Capital)/GarbageCollection.py                                       ggc.py
	ln -s $(Capital)/GeneratedConjureQuadruple.py                               gg4.py
	ln -s $(Capital)/Herd_2.py                                                  gh2.py
	ln -s $(Capital)/Herd_3.py                                                  gh3.py
	ln -s $(Capital)/Herd_4567.py                                               gh4.py
	ln -s $(Capital)/Herd.py                                                    ghe.py
	ln -s $(Capital)/HerdMany.py                                                ghm.py
	ln -s $(Capital)/Horde.py                                                   gho.py
	ln -s $(Capital)/Hailstone.py                                               gi.py
	ln -s $(Capital)/Global.py                                                  gl.py
	ln -s $(Capital)/LiquidMap.py                                               gq.py
	ln -s $(Capital)/Rabble.py                                                  gr.py
	ln -s $(Capital)/Series.py                                                  gse.py
	ln -s $(Capital)/Sequence.py                                                gsq.py
	ln -s $(PythonParser)/Parse.py                                              h0p.py
	ln -s $(PythonParser)/Parse1.py                                             h1p.py
	ln -s $(PythonParser)/Parse1Atom.py                                         h1pa.py
	ln -s $(PythonParser)/Parse1Call.py                                         h1pc.py
	ln -s $(PythonParser)/Parse1Expression.py                                   h1pe.py
	ln -s $(PythonParser)/Parse1ExpressionStatement.py                          h1pes.py
	ln -s $(PythonParser)/Parse1Function.py                                     h1pf.py
	ln -s $(PythonParser)/Parse1Import.py                                       h1pi.py
	ln -s $(PythonParser)/Parse1From.py                                         h1pm.py
	ln -s $(PythonParser)/Parse1Simple.py                                       h1ps.py
	ln -s $(PythonParser)/Parse1Complex.py                                      h1px.py
	ln -s $(PythonParser)/Tokenize1Atom.py                                      h1za.py
	ln -s $(PythonParser)/Tokenize1Header.py                                    h1zh.py
	ln -s $(PythonParser)/Tokenize1Name.py                                      h1zn.py
	ln -s $(PythonParser)/Tokenize1Operator.py                                  h1zo.py
	ln -s $(PythonParser)/Parse3.py                                             h3p.py
	ln -s $(PythonParser)/PrefixedDualStatement.py                              h2ps.py
	ln -s $(PythonParser)/DualStatement.py                                      h2s.py
	ln -s $(PythonParser)/DualToken.py                                          h2t.py
	ln -s $(PythonParser)/TernaryExpression.py                                  h3e.py
	ln -s $(PythonParser)/TripleStatement.py                                    h3s.py
	ln -s $(PythonParser)/TripleToken.py                                        h3t.py
	ln -s $(PythonParser)/QuadrupleFrill.py                                     h4f.py
	ln -s $(PythonParser)/QuadrupleStatement.py                                 h4s.py
	ln -s $(PythonParser)/QuadrupleToken.py                                     h4t.py
	ln -s $(PythonParser)/QuadrupleTwig.py                                      h4w.py
	ln -s $(PythonParser)/Atom.py                                               hat.py
	ln -s $(PythonParser)/BinaryExpression.py                                   hbe.py
	ln -s $(PythonParser)/BuildSymbolTable.py                                   hby.py
	ln -s $(PythonParser)/Cache.py                                              hca.py
	ln -s $(PythonParser)/Combine.py                                            hcb.py
	ln -s $(PythonParser)/CreateMeta.py                                         hcc.py
	ln -s $(PythonParser)/ClassOrder.py                                         hco.py
	ln -s $(PythonParser)/CallStatement.py                                      hcs.py
	ln -s $(PythonParser)/Core.py                                               hcr.py
	ln -s $(PythonParser)/Development.py                                        hd.py
	ln -s $(PythonParser)/DefinitionHeader.py                                   hdh.py
	ln -s $(PythonParser)/Elemental.py                                          hel.py
	ln -s $(PythonParser)/BookcaseExpression.py                                 hk.py
	ln -s $(PythonParser)/TokenCache.py                                         hkc.py
	ln -s $(PythonParser)/BookcaseDualExpression.py                             hkd.py
	ln -s $(PythonParser)/BookcaseDualStatement.py                              hkds.py
	ln -s $(PythonParser)/BookcaseManyFrill.py                                  hkf.py
	ln -s $(PythonParser)/BookcaseKeywordStatement.py                           hkk.py
	ln -s $(PythonParser)/BookcaseKeywordDualStatement.py                       hkkd.py
	ln -s $(PythonParser)/BookcaseManyExpression.py                             hkm.py
	ln -s $(PythonParser)/BookcaseManyStatement.py                              hkms.py
	ln -s $(PythonParser)/BookcaseStatement.py                                  hks.py
	ln -s $(PythonParser)/BookcaseTriple.py                                     hkt.py
	ln -s $(PythonParser)/Main.py                                               hma.py
	ln -s ../bin/.pyxie/hma.py                                                  hma1.py
	ln -s ../bin/.pyxie/hma2.py                                                 hma2.py
	ln -s $(PythonParser)/Match.py                                              hmc.py
	ln -s $(PythonParser)/MosiacDefinition.py                                   hmd.py
	ln -s $(PythonParser)/MemberExpression.py                                   hme.py
	ln -s $(PythonParser)/ManyFrill.py                                          hmf.py
	ln -s $(PythonParser)/Method.py                                             hmo.py
	ln -s $(PythonParser)/ManyExpression.py                                     hmx.py
	ln -s $(PythonParser)/MosiacSymbol.py                                       hmy.py
	ln -s $(PythonParser)/Priority.py                                           hpr.py
	ln -s $(PythonParser)/Pattern.py                                            hpt.py
	ln -s $(PythonParser)/Suite.py                                              hs.py
	ln -s $(PythonParser)/TupleOfExpression.py                                  hto.py
	ln -s $(PythonParser)/TokenTuple.py                                         htt.py
	ln -s $(PythonParser)/UnaryExpression.py                                    hu.py
	ln -s $(PythonParser)/Variable.py                                           hv.py
	ln -s $(PythonParser)/Whitespace.py                                         hwy.py
	ln -s $(PythonParser)/PostfixExpression.py                                  hx.py
	ln -s $(PythonParser)/SymbolTable.py                                        hy.py
	ln -s $(CodeGenerator)/Core.py                                              g1c.py
	ln -s $(CodeGenerator)/GenerateAscii.py                                     g1ga.py
	ln -s $(CodeGenerator)/GenerateTestPortrayString.py                         g1gt.py
	ln -s $(CodeGenerator)/Main.py                                              g1m.py
	ln -s $(CodeGenerator)/NestedConjure.py                                     g1n.py
	ln -s $(Capital)/__init__.py                                                in.py
	ln -s $(Capital)/Import.py                                                  im.py
	ln -s $(Capital)/IO.py                                                      io.py
	ln -s $(JavaParser)/Parse.py                                                j0p.py
	ln -s $(JavaParser)/Parse1.py                                               j1p.py
	ln -s ../Old/Junk/Boot.py                                                   jb.py
	ln -s $(JavaParser)/Core.py                                                 jcr.py
	ln -s $(JavaParser)/Main.py                                                 jma.py
	ln -s $(JavaParser)/Match.py                                                jmc.py
	ln -s $(JavaParser)/Pattern.py                                              jp.py
	ln -s $(KeyExample)/Euclid.py                                               ke.py
	ln -s $(KeyExample)/Main.py                                                 km.py
	ln -s $(KeyExample)/RSA_Example.py                                          kr.py
	ln -s log.txt                                                               l.txt
	ln -s $(LearningPython)/Main.py                                             lpm.py
	ln -s ../PPK/OtherLicenses/README.txt                                       lr1.txt
	ln -s Makefile                                                              m
	ln -s $(MultiProcessingExample)/Child.py                                    m2ch.py
	ln -s $(MultiProcessingExample)/Core.py                                     m2cr.py
	ln -s $(MultiProcessingExample)/Development.py                              m2d.py
	ln -s $(MultiProcessingExample)/Multiprocessing.py                          m2m.py
	ln -s $(MultiProcessingExample)/Main.py                                     m2ma.py
	ln -s $(Capital)/Map.py                                                     map.py
	ln -s $(Capital)/Method.py                                                  me.py
	ln -s $(Capital)/Output.py                                                  o.py
	ln -s $(CoreParser)/DualFrill.py                                            p2f.py
	ln -s $(CoreParser)/TripleFrill.py                                          p3f.py
	ln -s $(CoreParser)/DualTwig.py                                             p2w.py
	ln -s $(CoreParser)/TripleTwig.py                                           p3w.py
	ln -s $(Capital)/Path2.py                                                   pa2.py
	ln -s $(CoreParser)/Atom.py                                                 pat.py
	ln -s $(Capital)/Path.py                                                    path.py
	ln -s $(CoreParser)/ActionWord.py                                           paw.py
	ln -s $(CoreParser)/Cache.py                                                pca.py
	ln -s $(CoreParser)/CreateMeta.py                                           pcc.py
	ln -s $(CoreParser)/ClassOrder.py                                           pco.py
	ln -s $(CoreParser)/Core.py                                                 pcr.py
	ln -s $(CoreParser)/DumpToken.py                                            pdt.py
	ln -s $(CoreParser)/EmptyLine.py                                            pel.py
	ln -s $(CoreParser)/Elemental.py                                            pem.py
	ln -s $(CoreParser)/Tokenizer.py                                            pf.py
	ln -s $(CoreParser)/BookcaseDualTwig.py                                     pk2.py
	ln -s $(CoreParser)/BookcaseCoupleTwig.py                                   pk2c.py
	ln -s $(CoreParser)/TokenCache.py                                           pkc.py
	ln -s $(CoreParser)/LineMarker.py                                           pl.py
	ln -s $(CoreParser)/Method.py                                               pm.py
	ln -s $(CoreParser)/Nub.py                                                  pn.py
	ln -s ../Old/Junk/PortrayString_3.py                                        ps3.py
	ln -s $(CoreParser)/TestTree.py                                             ptt.py
	ln -s $(CoreParser)/CrystalComment.py                                       pyc.py
	ln -s $(CoreParser)/CrystalIndentation.py                                   pyi.py
	ln -s $(CoreParser)/ParserToken.py                                          pyk.py
	ln -s $(CoreParser)/ParserTrunk.py                                          pyt.py
	ln -s $(SqlParser)/Parse1.py                                                q1p.py
	ln -s $(SqlParser)/Comment.py                                               qcm.py
	ln -s $(SqlParser)/Core.py                                                  qcr.py
	ln -s $(SqlParser)/ConjureTreeComment.py                                    qj.py
	ln -s $(SqlParser)/Line.py                                                  ql.py
	ln -s $(SqlParser)/Main.py                                                  qma.py
	ln -s $(SqlParser)/Match.py                                                 qmc.py
	ln -s $(SqlParser)/Pattern.py                                               qp.py
	ln -s $(SqlParser)/Statement.py                                             qs.py
	ln -s $(TremoliteParser)/Parse.py                                           r0p.py
	ln -s $(TremoliteParser)/Parse1.py                                          r1p.py
	ln -s $(Restructure)/CreateMatch.py                                         rcm.py
	ln -s $(TremoliteParser)/Core.py                                            rcr.py
	ln -s $(Restructure)/Core.py                                                rcr2.py
	ln -s $(TremoliteParser)/Development.py                                     rd.py
	ln -s $(Capital)/RegularExpression.py                                       re.py
	ln -s $(TremoliteParser)/Elemental.py                                       rel.py
	ln -s ../Tremolite/OtherLicenses/LicenseTemplate.txt                        rlp.txt
	ln -s ../Tremolite/OtherLicenses/README.txt                                 rlr.txt
	ln -s $(TremoliteParser)/Main.py                                            rma.py
	ln -s $(Restructure)/Main.py                                                rma2.py
	ln -s $(TremoliteParser)/Match.py                                           rmc.py
	ln -s $(Restructure)/Match.py                                               rmc2.py
	ln -s $(Restructure)/Name.py                                                rn.py
	ln -s $(TremoliteParser)/Pattern.py                                         rp.py
	ln -s $(TremoliteParser)/Statement.py                                       rs.py
	ln -s $(Restructure)/Build.py                                               ru.py
	ln -s $(Rex)/Compile.py                                                     rxc.py
	ln -s $(Rex)/Core.py                                                        rxcr.py
	ln -s $(Rex)/Parse.py                                                       rxp.py
	ln -s $(Rex)/PatternWrapper.py                                              rxw.py
	ln -s $(Capital)/Sleep.py                                                   sl.py
	ln -s $(Capital)/StringOutput.py                                            so.py
	ln -s $(Capital)/SimpleStringIO.py                                          ssio.py
	ln -s $(Capital)/System.py                                                  sy.py
	ln -s test.java                                                             t.java
	ln -s test.py                                                               t1.py
	ln -s test2.py                                                              t2.py
	ln -s $(Capital)/Traceback.py                                               tb.py
	ln -s $(Capital)/Thread.py                                                  th.py
	ln -s $(Rubber)/Core.py                                                     uc.py
	ln -s $(Rubber)/Development.py                                              ud.py
	ln -s $(Rubber)/ElasticSearch.py                                            ue.py
	ln -s $(Rubber)/Main.py                                                     um.py
	ln -s $(SinglePythonFileBoot)/SinglePythonFileBoot.py                       xb.py
	ln -s $(PythonParser)/Transform.py                                          xf.py
	ln -s $(Chess5x2)/Board.py                                                  ybd.py
	ln -s $(Chess5x2)/ChessBishop.py                                            ybi.py
	ln -s $(Chess5x2)/BlankSquare.py                                            ybq.py
	ln -s $(Chess5x2)/CardRoot.py                                               ycb.py
	ln -s $(Chess5x2)/Core.py                                                   ycr.py
	ln -s $(Chess5x2)/Deck_7.py                                                 yd7.py
	ln -s $(Chess5x2)/Game.py                                                   yg.py
	ln -s $(Chess5x2)/ChessKing.py                                              yki.py
	ln -s $(Chess5x2)/ChessKnight.py                                            ykn.py
	ln -s $(Chess5x2)/Main.py                                                   ym.py
	ln -s $(Chess5x2)/Player.py                                                 yp.py
	ln -s $(Chess5x2)/Square.py                                                 yq.py
	ln -s $(Chess5x2)/ChessRook.py                                              yr.py
	ln -s $(Capital)/PortrayString.py                                           ys.py
	ln -s $(Chess5x2)/VoidSquare.py                                             yv.py
	ln -s $(Chess5x2)/ChessPawn.py                                              yw.py
	ln -s $(Chess5x2)/FrozenChessCard.py                                        yzc.py
	ln -s $(Chess5x2)/FrozenCardRoot.py                                         yzr.py
	ln -s $(UnitTest)/Core.py                                                   zcr.py
	ln -s $(UnitTest)/CacheSupport.py                                           zcs.py
	ln -s $(UnitTest)/Drove.py                                                  zd.py
	ln -s $(UnitTest)/ExceptionChain.py                                         ze.py
	ln -s $(UnitTest)/GeneratedConjureDual.gpy                                  zg2.gpy
	ln -s $(UnitTest)/GeneratedConjureDual.py                                   zg2.py
	ln -s $(UnitTest)/GeneratedConjureTriple.gpy                                zg3.gpy
	ln -s $(UnitTest)/GeneratedConjureTriple.py                                 zg3.py
	ln -s $(UnitTest)/GeneratedConjureQuadruple.gpy                             zg4.gpy
	ln -s $(UnitTest)/GeneratedConjureQuadruple.py                              zg4.py
	ln -s $(UnitTest)/GeneratedNew.gpy                                          zgn.gpy
	ln -s $(UnitTest)/GeneratedNew.py                                           zgn.py
	ln -s $(UnitTest)/Herd.py                                                   zh.py
	ln -s $(UnitTest)/ConjureSingle.py                                          zj1.py
	ln -s $(UnitTest)/ConjureDual.py                                            zj2.py
	ln -s $(UnitTest)/ConjureTriple.py                                          zj3.py
	ln -s $(UnitTest)/ConjureQuadruple.py                                       zj4.py
	ln -s $(UnitTest)/ConjureTreeComment.py                                     zjtc.py
	ln -s $(UnitTest)/Main.py                                                   zm.py
	ln -s $(UnitTest)/OldConjureQuadruple.py                                    zo4.py
	ln -s $(UnitTest)/Path.py                                                   zpa.py
	ln -s $(UnitTest)/Pattern.py                                                zpt.py
	ln -s $(UnitTest)/Series.py                                                 zse.py
	ln -s $(UnitTest)/StringOutput.py                                           zso.py
	ln -s $(UnitTest)/Sequence.py                                               zsq.py
	ln -s $(UnitTest)/PortrayString.py                                          zys.py


wc:
	#
	#  Excludes $(Agate_Files) and $(*_GENERATED)
	#
	wc -l \
        $(Beryl_Files) \
        $(Capital_Files) \
        $(Chess5x2_Files) \
        $(CodeGenerator_Files) \
        $(CoreParser_Files) \
        $(JavaParser_Files) \
        $(KeyExample_Files) \
        $(LearningPython_Files) \
        $(License_Files) \
        $(LockFree_Files) \
        $(MultiProcessingExample_Files) \
        $(PythonParser_Files) \
        $(Remedy_Files) \
        $(Restructure_Files) \
        $(Rex_Files) \
        $(Rubber_Files) \
        $(SinglePythonFileBoot_Files) \
        $(SqlParser_Files) \
        $(TremoliteParser_Files) \
        $(UnitTest_Files) \
        $(Work_Files)


test:
	cat \
        $(Beryl_Files) \
        $(Capital_Files) \
        $(Chess5x2_Files) \
        $(CodeGenerator_Files) \
        $(CoreParser_Files) \
        $(JavaParser_Files) \
        $(KeyExample_Files) \
        $(LearningPython_Files) \
        $(LockFree_Files) \
        $(MultiProcessingExample_Files) \
        $(PythonParser_Files) \
        $(Remedy_Files) \
        $(Restructure_Files) \
        $(Rex_Files) \
        $(Rubber_Files) \
        $(SinglePythonFileBoot_Files) \
        $(SqlParser_Files) \
        $(TremoliteParser_Files) \
        $(UnitTest_Files) \
            >test.py
	python hma.py
